In [3]:
import numpy as np

In [4]:
mylist = [1,2,3]

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
nested_list = [[1,2], [3,4], [5,6]]

In [7]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [8]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.zeros((4,4), dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [20]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(2)

array([0.17454016, 0.21043577])

In [26]:
np.random.rand(3, 4)

array([[0.27331647, 0.48966142, 0.87204677, 0.55155728],
       [0.68383031, 0.83413774, 0.65660299, 0.20645838],
       [0.28041162, 0.49719307, 0.15473973, 0.44422359]])

In [27]:
np.random.randn(5,5)

array([[ 2.66091879, -1.14880538, -0.61240887, -0.55464747,  3.02926984],
       [-0.02564692,  1.13594602,  0.65433001,  0.9502624 ,  0.10411481],
       [-0.92405134,  0.66448433, -1.51182187,  1.51151629, -0.29012732],
       [-1.16171866, -0.18226139,  0.31296956, -0.12452906,  0.83662601],
       [-1.1461443 , -0.57771482, -0.39003418,  1.26424272,  1.81230956]])

In [28]:
np.random.randint(1,100)

56

In [29]:
np.random.randint(1,100, (2,3))

array([[ 8, 37, 87],
       [62, 31,  2]])

In [33]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [34]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [35]:
arr = np.arange(25)

In [36]:
ranarr = np.random.randint(0,50,10)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [39]:
arr.shape

(25,)

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr.reshape(3,6)

ValueError: cannot reshape array of size 25 into shape (3,6)

In [44]:
ranarr

array([35, 39, 23,  2, 21,  1, 23, 43, 29, 37])

In [45]:
ranarr.max()

43

In [46]:
ranarr.argmax()

7

In [47]:
ranarr.min()

1

In [48]:
ranarr.argmin()

5

In [49]:
ranarr.dtype

dtype('int64')

In [50]:
myarr = np.random.rand(4)

In [51]:
myarr

array([7.78765841e-04, 9.92211559e-01, 6.17481510e-01, 6.11653160e-01])

In [52]:
myarr.dtype

dtype('float64')